name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Generate javadoc
      run: mvn javadoc:javadoc
        
      # https://github.com/marketplace/actions/get-tag-name
    - name: Get tag name
      uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
          tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
        
    
    - name: create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.tagName.outputs.tag }}"          
          prerelease: false
          # Release title; defaults to the tag name if none specified.
          files: |
            ./target/statique-?.?.?.jar
            ./target/site/
