name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build with Maven
      run: |
        echo "-----HHHHHHHHHHHHHHHHHHHHHHHH------------"
        ls
        echo "-----HHHHHHHHHHHHHHHHHHHHHHHH------------"
                
    - name: Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          # Release title; defaults to the tag name if none specified.
          files:
            target/*.jar      
